config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "pages#home"
  get 'about', to: "pages#about"
  resources :articles#, only: [:show, :index, :new, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: {minimum: 6, maximum: 100}
  validates :description, presence: true, length: {minimum: 10, maximum: 500}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy ]

  def index 
    @articles = Article.all
  end

  def show    
  end

  def new
   @article = Article.new
  end

  def create
    @article =  Article.new(article_params)
    if @article.save
      flash[:notice] = "Article is created successfully"
      redirect_to @article
    else
      render 'new'
    end
  end

  
  def edit
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was created successfully."
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    flash[:success] = "The article is deleted successfully. "
    redirect_to articles_path
  end


  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= article.description %>
  </p>

</div>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<ul>
  <% @article.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>
<% end %>


<%= form_with(model: @article, local: true) do |f| %>  
<p>
  <strong><%= f.label :title %></strong> <br>
  <%= f.text_field :title %>
</p>

<p>
  <strong><%= f.label :description %></strong><br>
  <%= f.text_area :description %>
</p>

<p>
  <%= f.submit  %>
</p>


<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

<%= link_to 'Cancel and return to articles listing', articles_path %>

app/views/articles/index.html.erb
<h1>Articles listing page</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

    <% @articles.each do |article| %>
      <tbody>
        <tr>
          <td><%= article.title %></td>
          <td><%= article.description%></td>
          <td><%= link_to 'Show', article_path(article) %></td>
          <td><%= link_to 'Update', edit_article_path(article) %></td>
          <td><%= link_to 'Delete', article_path(article), data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
          } %></td>
        </tr>
      </tbody>
    <% end %>
</table>


<p>
  <%= link_to 'Create new article',  new_article_path %>
</p>

app/views/articles/new.html.erb
<h1>Create a new Article</h1>
<%= render 'form' %>
<!-- 
<% if @article.errors.any? %>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>


<%= form_with scope: :article, url: articles_path, local: true do |f| %>  
  <p>
    <strong><%= f.label :title %></strong> <br>
    <%= f.text_field :title %>
  </p>

  <p>
    <strong><%= f.label :description %></strong><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit 'Create article'  %>
  </p>
  
<% end %> -->

<%= link_to 'Return to articles listing', articles_path %>

app/views/articles/show.html.erb
<h1>Showing article details</h1>

<p><strong>Title: </strong> <%= @article.title %></p>

<p><strong>Description: </strong> <%= @article.description %> </p>

<%= link_to 'Edit', edit_article_path(@article)  %>
<%= link_to 'Delete', article_path(@article),  data: {
  turbo_method: :delete,
  turbo_confirm: "Are you sure?"}  %> |
<%= link_to 'Return to articles listing', articles_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg|%>
  <%= msg %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloWorld</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Welcome to the Homepage</h1>

<%= link_to 'Articles listing', articles_path %> | 

<%= link_to 'Home Page', root_path %>

app/views/pages/home.html.erb
<h1>Welcome to the Homepage</h1>

<%= link_to 'Articles listing', articles_path %> | 

<%= link_to 'About Page', about_path %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>